### ISSUE TITLE
vqmod nested require

### ISSUE THREAD

**Issue by trueliarx** [codexilab/osclass-vqmod#4]
Hello,
I've tried to modify files that are required (require_once()) in osclass but I found out that vqmod doesn't work withouth VQMod::modCheck().

Osclass have a lot of require_once and practically it's very difficult to create efficient mods.

https://stackoverflow.com/questions/29364627/vqmod-nested-require-once

Do you have a smarter solution than replacing all the necessary occurrences (of require_once) ?

regards

**Comment by codexilab** [comment]
> vqmod doesn't work withouth VQMod::modCheck().

Obviously.

> Do you have a smarter solution than replacing all the necessary occurrences (of require_once) ?

It could be with namespaces, but I have not tested if vQmod has scope with php's namespaces.
